{
  "openapi": "3.0.0",
  "info": {
    "title": "Classificação de Risco de Saúde Mental API",
    "description": "Está documentação visa esclarecer o uso dos endpoints da API de classificação de risco de saúde mental.<br><br>Fique atento aos 'cadeados' nos endpoints, isso denota rotas que necessitam de autenticação.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api-risco-saude-mental.herokuapp.com",
      "description": "API de produção"
    },
    {
      "url": "http://localhost:3000",
      "description": "API de desenvolvimento"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "description": "Rota para login qualquer tipo de funcionário",
        "tags": ["Login"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              },
              "examples": {
                "admin": {
                  "value": {
                    "email": "admin@admin.com",
                    "password": "1234"
                  }
                },
                "doctor": {
                  "value": {
                    "email": "doctor@doctor.com",
                    "password": "1234"
                  }
                },
                "nurse": {
                  "value": {
                    "email": "nurse@nurse.com",
                    "password": "1234"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Este erro ocorre quando algum campo necessário não é enviado no body da requisição ou o tipo de dado de algum campo é diferente do esperado, veja o schema do body.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse400"
                },
                "examples": {
                  "credenciais_nao_enviadas": {
                    "value": {
                      "error": [
                        "email is a required field",
                        "password is a required field"
                      ]
                    }
                  },
                  "email_enviado_como_array": {
                    "value": {
                      "error": [
                        "email must be a `string` type, but the final value was: `[\n  \"\\\"doctor@email.com\\\"\"\n]`."
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Este erro ocorre quando as credenciais enviadas são inválidas.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse401"
                },
                "examples": {
                  "credenciais_invalidas": {
                    "value": {
                      "message": "Invalid credentials"
                    }
                  }
                }
              }
            }
          },
          "200": {
            "description": "Login realizado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse200"
                },
                "examples": {
                  "sucesso": {
                    "value": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAzOTQ2NjFhLTAwODktNGM1Ni1iNGZiLTdhZTBiZTQ1YzJhOSIsImVtYWlsIjoiZG9jdG9yQGVtYWlsLmNvbSIsImlhdCI6MTY1NTkzOTQzOSwiZXhwIjoxNjU1OTQzMDM5fQ.2tY9XWLmpB2J4EmS91K7s3Qk9Xt7BZBabct5NDuf23w"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/admin/clients": {
      "get": {
        "description": "Route to client listing",
        "tags": ["Admin"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Listing successful clients",
            "content": {
              "application/json": {
                "examples": {
                  "clients": {
                    "value": {
                      "clients": [
                        {
                          "id": "50ce3967-4966-485e-9876-5eae0bbb3e06",
                          "name": "John Doe 2",
                          "subscription": "1432193",
                          "data": {
                            "id": "cd88e8aa-e1b6-4a85-bdc5-86515f1764c0",
                            "cpf": "892.762.670-26",
                            "birthday": "10/10/2012",
                            "gender": "F",
                            "email": "johndoe@email.com",
                            "mobile": "(89) 4184-1510",
                            "street": "Nowhere St. Pedro",
                            "number": "15",
                            "complement": "apt. 9990",
                            "zip": "06310-320",
                            "city": "San Angels Del Atacama",
                            "state": "DF"
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "This error occurs when a non-admin employee tries to access the customer list",
            "content": {
              "application/json": {
                "examples": {
                  "unauthorized_employee": {
                    "value": {
                      "message": "Only admins are allowed to access this route."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/admin/employees": {
      "get": {
        "description": "Route to employee listing.",
        "tags": ["Admin"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Listing successful employees",
            "content": {
              "application/json": {
                "examples": {
                  "clients": {
                    "value": {
                      "employees": [
                        {
                          "id": "0394661a-0089-4c56-b4fb-7ae0be45c2a9",
                          "name": "John Dow",
                          "specialty": "Psychiatry",
                          "job": "Doctor",
                          "register": "1111111113",
                          "isActive": true,
                          "data": {
                            "id": "cd88e8aa-e1b6-4a85-bdc5-86515f1764c0",
                            "cpf": "892.762.670-26",
                            "birthday": "10/10/2012",
                            "gender": "F",
                            "email": "johndoe@email.com",
                            "mobile": "(89) 4184-1510",
                            "street": "Nowhere St. Pedro",
                            "number": "15",
                            "complement": "apt. 9990",
                            "zip": "06310-320",
                            "city": "San Angels Del Atacama",
                            "state": "DF"
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "This error occurs when a non-admin employee tries to access the customer list",
            "content": {
              "application/json": {
                "examples": {
                  "unauthorized_employee": {
                    "value": {
                      "message": "Only admins are allowed to access this route."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/admin/procedures/{risk}": {
      "get": {
        "description": "Route to get procedure according to mental health risk level",
        "tags": ["Admin"],
        "parameters": [
          {
            "name": "risk",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "description": "Mental health risk level",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Procedure successfully obtained",
            "content": {
              "application/json": {
                "examples": {
                  "grave": {
                    "value": {
                      "procedure": "Priority targeting, immediate clinical care."
                    }
                  },
                  "elevated": {
                    "value": {
                      "procedure": "Immediate classification, clinical care without immediate risk of life."
                    }
                  },
                  "moderated": {
                    "value": {
                      "procedure": "Treatment at CAPS and outpatient clinic specializing in mental health."
                    }
                  },
                  "low": {
                    "value": {
                      "procedure": "Care in the primary health care network."
                    }
                  },
                  "nonspecific": {
                    "value": {
                      "procedure": "No need for medical attention."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "This error occurs when an invalid risk is entered as a parameter.",
            "content": {
              "application/json": {
                "examples": {
                  "risk not exists": {
                    "value": {
                      "message": "Risk does not exist."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "LoginRequest": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "LoginResponse200": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          }
        }
      },
      "LoginResponse400": {
        "type": "object",
        "properties": {
          "error": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "LoginResponse401": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      }
    }
  }
}
